sudo: required

language: node_js

node_js:
  - "node"

services:
  - docker

script:
  - npm test

after_success:
  - echo "$TRAVIS_TAG"
  - echo "$TRAVIS_BRANCH"
  - if [ "$TRAVIS_TAG" == "v0.1.3" ]; then echo "please push" fi
  - echo "ok"
