sudo: required

language: node_js

node_js:
  - "node"

services:
  - docker

script:
  - npm test

after_success:
  - echo "$TRAVIS_TAG"
  - echo "$TRAVIS_BRANCH"
  - if [ -z "$TRAVIS_BRANCH" ]; then
      echo "no need to push";
    else
      docker build -t auth0blog/bang-bang .;
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker push auth0blog/bang-bang;
    fi;
